name: Codestyle

on:
  workflow_run:
    workflows: [ "Build" ]
    branches: [ * ]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 1.17
      - name: Maven Verify
        run: mvn checkstyle:check
